name: GHES Acceptance Tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2

      - name: Acceptance Tests
        uses: terraformtesting/acceptance-tests@v2.0.0
        with:
          RUN_ALL: true
          GITHUB_BASE_URL: "https://terraformtesting-ghe.eastus.cloudapp.azure.com/"
          GITHUB_OWNER: terraformtesting
